### PR TITLE
Restructuring SANDS repo

### PR DESCRIPTION
**Pull request by UlrikeS91**
--> SANDS/v0.1/ to SANDS/v1.0/
--> removed SANDS/v0.1/core/ and SANDS/v0.1/elements/ (all schemas are now in SANDS/v1.0/)

### CODE REVIEW

**Review by lzehl — APPROVED** [review]
Note: The references in the definitions file still need to be corrected according to the new structure.

Can be handled in a second PR, though.

**Comment by lzehl** [comment]
@UlrikeS91 sorry I think I messed up the order of the PRs could you resolve the conflicts? I think this is due to the PR which I just merged that changed the `@type` to be capitalized (e.g., "BrainAtlas" instead of "brainAtlas"). This PR was done based on a discussion and decision I made with @olinux

**Comment by lzehl** [comment]
@UlrikeS91 could you please put the controlledTerm.schema.json in its own subdirectory "controlledTerms/"?  
This is based on a discussion and decision I made together with @olinux

**Comment by UlrikeS91** [comment]
> @UlrikeS91 sorry I think I messed up the order of the PRs could you resolve the conflicts? I think this is due to the PR which I just merged that changed the `@type` to be capitalized (e.g., "BrainAtlas" instead of "brainAtlas"). This PR was done based on a discussion and decision I made with @olinux

Yeah...fixing it will be more work than just making a new PR...I'll close this one then.

> @UlrikeS91 could you please put the controlledTerm.schema.json in its own subdirectory "controlledTerms/"?
> This is based on a discussion and decision I made together with @olinux

I don't understand want you mean by this. SANDS doesn't have the `controlledTerm.schema.json`. The only place it is referenced is in `definitions.json`. So, do you mean that the schema will be moved to it's on subfolder in the openMINDS repo and therefore the ref in the definitions-file here in SANDS needs to be updated?

**Pull request closed without merging**
