### PR TITLE
Fix JSON syntax errors and add github CI to prevent future syntax errors

### PR DESCRIPTION
**Pull request by xgui3783**
chore: fixed json syntax errors
chore: added github CI to check for json syntax err

### CODE REVIEW

**Comment by xgui3783** [comment]
maybe related #38 

I would have imagined latter version of schema validator will be backwards compatible to previous versions of schema? Though admittedly I don't know for sure.

**Comment by UlrikeS91** [comment]
@skoehnen Has this PR been dealt with? It hasn't been merged and I'm reluctant to review it, because I know too little about e.g. the validator. Could you deal with this?

**Comment by lzehl** [comment]
@xgui3783 there seems to be a conflict. Could you resolve this?

**Comment by xgui3783** [comment]
@lzehl done

**Review by lzehl — APPROVED** [review]
@skoehnen looks good to me. If you agree this can be merged

**Review by skoehnen — APPROVED** [review]
Looks good to me

**Pull request merged**
